server:
  host: "0.0.0.0"
  port: 8080

modules:
  detector:
    type: "yunet" # "scrfd"
    workers:  2
  tracker:
    type: "bytetrack"
    bytetrack:
      high_thresh: 0.6
      low_thresh: 0.1
      new_track_thresh: 0.7
      match_iou_thresh: 0.8
      low_match_iou_thresh: 0.5
      unconfirmed_match_iou_thresh: 0.7
      duplicate_iou_thresh: 0.85
      track_buffer: 30
      min_box_area: 10.0
      fuse_score: true

metrics:
  enabled: true
  enable_http: true
  enable_ui_payload: true
  log_interval_ms: 5000

streams:
#  - id: "rtsp0"
#    type: "rtsp"
#
#    rtsp:
#      url: "rtsp://rtspstream:iC_SMRxQh3s8d66xv1LBW@zephyr.rtsp.stream/pattern"
#      tcp: true
#      latency_ms: 1000
#
#    outputs:
#      profiles:
#        inference:
#          width: 960
#          height: 540
#          fps: 10
#          format: "BGR"
#        ui:
#          width: 960
#          height: 540
#          fps: 10
#          jpeg_quality: 75
#
#    replicate:
#      count: 2
#
  - id: "cam0"
    type: "webcam"

    webcam:
      device: "/dev/video0"
      width: 1280
      height: 720
      fps: 15
      mjpg: true

    outputs:
      profiles:
        inference:
          width: 640
          height: 640
          fps: 15
          format: "BGR"
        ui:
          width: 1280
          height: 720
          fps: 15
          jpeg_quality: 75

    replicate:
      count: 1

#  - id: "file0"
#    type: "file"
#
#    file:
#      path: "../../../assets/store.mp4"
#      fps: 5
#
#    outputs:
#      fps: 10
#      profiles:
#        inference:
#          width: 640
#          height: 640
#          format: "BGR"
#        ui:
#          width: 1280
#          height: 720
#          jpeg_quality: 75
#
#    replicate:
#      count: 2
